[package]
name = "cursive_react"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0", features = ["backtrace"] }
cursive = "^0.21"
cursive_table_view = "0.15"

[[example]]
name = "counter-app"

[[example]]
name = "sisko-app"

[[example]]
name = "stack-app"
